name: 'btapi GitHub Actions'
#defaults: #
#  run:
#    working-directory: "pra-btapi"
on:
  - pull_request
  - push
jobs:
  pra:
    name: 'PRA'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'CI/CD Pipeline with btapi'
        env:
          BT_CLIENT_ID: ${{ secrets.BT_CLIENT_ID }}
          BT_CLIENT_SECRET: ${{ secrets.BT_CLIENT_SECRET }}
          BT_API_HOST: ${{ secrets.BT_API_HOST }}
        run: |
          curl -o btapi.zip -L https://apra.beyondtrustcloud.com/api/config/v1/cli/linux
          unzip btapi.zip
          mv btapi /usr/local/bin
          rm btapi.zip
          retrv1=$(btapi do vault/account/61/check-out | jq '.password')
          retrv2=$(btapi do vault/account/62/check-out | jq '.password')
          retrv3=$(btapi do vault/account/63/check-out | jq '.password')
          retrv4=$(btapi do vault/account/64/check-out | jq '.password')
          tee > /dev/null 2>&1 app01/keys.tf <<EOF > /dev/null 2>&1
            variable s_id {
              default = $retrv1
            }
            variable c_id {
              default = $retrv2
            }
            variable c_sec {
              default = $retrv3
            }
            variable t_id {
              default = $retrv4
            }
          EOF
          btapi do vault/account/61/check-in
          btapi do vault/account/62/check-in
          btapi do vault/account/63/check-in
          btapi do vault/account/64/check-in
      - name: 'Terraform Init'
        id: init
        run: terraform init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Terraform Validate'
        id: validate
        run: terraform validate
      - name: 'Terraform Plan'
        id: plan
        run: terraform plan
        continue-on-error: true 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Terraform Apply'
        id: apply
        run: terraform apply -auto-approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
